### ISSUE TITLE
In or Not In clause

### ISSUE THREAD

**Issue by hanpera** [sebastienros/yessql#255] opened 2020-07-08 13:12 UTC
Hi,
I am not able to build a clause "value IN (value1, value2....)
Usually in EF I was able to write this clause like

string[] values = new[]{"value1", "value2"...}
var results = query.Where(r => values.Contains(r.Value)

If I write a similar clause with yessql the result is that the variable r is out of scope in session
Thanks in advance

Andrea

**Comment by deanmarcussen** [comment] 2020-07-08 13:18
Ah duplicate of your other issue.

I think you can close them both

You need to use the correct extension method

example 
```
using YesSql.Services;
query.Where(x => x.ContentType.IsIn(values));
```

**Closed** 2020-07-14 10:26 UTC
